### ISSUE TITLE
Error with loading program

### ISSUE THREAD

**Issue by sausageunicorns** [imchillin/SSTool#4]
With the latest patch, I get an error now when I start up the program.
"Couldn't run the updater.  Would you like to visit the releases page to check for a new update manually?"
I tried running SSToolsUpdater, it'll report it is up to date.  When I click on 'Open FFXIVTool' - it'll repeat the previously mentioned error.  The most major issue I see is I cannot search, or load weapons while using the tool.  I haven't found any other issue yet.
![error](https://user-images.githubusercontent.com/57426631/68265988-a58fc080-001b-11ea-8f4e-fe77611d3753.PNG)

**Comment by LeonBlade** [comment]
Go download the latest release, also the new branch is CMTool now.
